In [0]:
import numpy as np
a_ndarray = np.array([[-1 , 2 , 3] , [4 , -5 , 6 ] , [7,  8, -9 ]])
b_ndarray = np.array([[0 , 2 , 1 ] , [0 , 2 , -8 ] , [2 , 9 , -1 ]])

# 問１ 行列積を手計算する

In [0]:
a_ndarray = np.array([[ -1 , 2 , 3] , [4 , -5 , 6 ] , [7,  8, -9 ]])
b_ndarray = np.array([[0 , 2 , 1 ] , [0 , 2 , -8 ] , [2 , 9 , -1 ]])



In [0]:
ab1 = (-1 * 0) + (2 * 0) + (3 * 2)
ab2 = (-1 * 2) + (2 * 2) + (3 * 9)
ab3 = (-1 * 1) + (2 * -8) + (3 * -1)
ab4 = (4 * 0) + (-5 * 0) + (6 * 2)
ab5 = (4 * 2) + (-5 * 2) + (6 * 9)
ab6 = (4 * 1) + (-5 * -8) + (6 * -1)
ab7 = (7 * 0) + ( 8 * 0) + (-9 * 2)
ab8 = (7 * 2) + ( 8 * 2) + (-9 * 9)
ab9 = (7 * 1) + ( 8 * -8) + (-9 * -1)

In [5]:
print(ab1,ab2,ab3,ab4,ab5,ab6,ab7,ab8,ab9)
ab_list_ndarray = np.array([[ab1,ab2,ab3],[ab4,ab5,ab6],[ab7,ab8,ab9]])
print(ab_list_ndarray)

6 29 -20 12 52 38 -18 -51 -48
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


行列A
|a11 a12 a13|
|a21 a22 a23|
|a31 a32 a33|

行列B
|b11 b12 b13|
|b21 b22 b23|
|b31 b32 b33|

があったとき、
A×Bは
|a11×b11+a12×b21+a13×b31,
a11×b12+a12×b22+a13×b32,
a11×b13+a12×b23+a13×b33|,
|a21×b11+a22×b21+a23×b31,
a21×b12+a22×b22+a23×b32,　a21×b13+a22×b23+a23×b33|,
|a31×b11+a32×b21+a33×b31,
a31×b12+a32×b22+a33×b32,
a31×b13+a32×b23+a33×b33|


# 問２ NumPyの関数による計算

In [6]:
a = np.array([[ -1 , 2 , 3] , [4 , -5 , 6 ] , [7,  8, -9 ]])
b = np.array([[0 , 2 , 1 ] , [0 , 2 , -8 ] , [2 , 9 , -1 ]])
np.matmul(a, b)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [7]:
c = np.dot(a, b)
print("AとBの行列積は：{}".format(c))

AとBの行列積は：[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [13]:
c = a @ b
print("AとBの行列積は:{}".format(c))

AとBの行列積は:[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 問３ ある要素の計算を実装

In [9]:
a_ndarray = [[-1 , 2 , 3] , [4 , -5 , 6 ] , [7,  8, -9 ]]
b_ndarray = [[0 , 2 , 1 ] , [0 , 2 , -8 ] , [2 , 9 , -1 ]]


result = []
for e , f, g in a_ndarray:
    result_2 = []
    for ee , ff, gg in zip(* b_ndarray):
        result_2.append(e * ee + f * ff + g * gg)
    result.append(result_2)
print(result[0][0])

6


# 問４ 行列積を行う関数の作成

In [10]:
a_ndarray = [[-1 , 2 , 3] , [4 , -5 , 6 ] , [7,  8, -9 ]]
b_ndarray = [[0 , 2 , 1 ] , [0 , 2 , -8 ] , [2 , 9 , -1 ]]


result = []
def ab_ndarray(a , b):
    for e , f , g in a:
        result_2 = []
        for ee , ff , gg in zip(* b):
            result_2.append(e * ee + f * ff + g * gg)
        result.append(result_2)
    return result


ab_ndarray(a_ndarray , b_ndarray)

[[6, 29, -20], [12, 52, 38], [-18, -51, -48]]

# 問５ 計算が定義されない入力を判定する

In [26]:
def ab_ndarray(a, b):
    c = np.empty((a.shape[0], b.shape[1]))

    if a.shape[1] == b.shape[0]:
        c = (a[:, np.newaxis, :]*b.T).sum(axis=2)
        return c
    else:
        print("a.shape[1] != b.shape[0] : {} != {}".format(a.shape[1], b.shape[0]))
        return None
        
d = np.array([[-1, 2, 3], [4, -5, 6]])
e = np.array([[-9, 8, 7], [6, -5, 4]])
print("計算結果\n{}".format(ab_ndarray(d, e)))

a.shape[1] != b.shape[0] : 3 != 2
計算結果
None


# 問６ 転置

In [28]:
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])


print("計算結果：{}".format(d.T@e))
print("計算結果：{}".format(d@e.T))

計算結果：[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
計算結果：[[ 46  -4]
 [-34  73]]
