## オブジェクト指向の活用

In [2]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]


## 【問題1】これまで利用してきたクラスの列挙


* pandas

DataFrame : 二次元のデータ構造を持つクラス

* matplotlib

patchesクラス: matplotlibの簡易的な図形描写モジュール

colorsクラス: Matplotlibで色をコントロールするモジュール

* scikit-learn

datasets : アヤメの品種データやボストン市の住宅価格データなどのデータが格納されているデータセットモジュール

`StandardScaler`, `KNeighborsClassifier`

In [3]:
print(type(100))
print(type("aaa"))
print(type(type(100)))

<class 'int'>
<class 'str'>
<class 'type'>


In [4]:
import pandas as pd
print(type(pd.DataFrame))
print(type(pd.DataFrame()))

<class 'type'>
<class 'pandas.core.frame.DataFrame'>


In [5]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]


## 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙


## メソッド

*・数値計算系*

sum(), max(), min(), abs(), round()

*・型関連*

dict(), int(), float(), set(), list(), str(), tuple(), type(), 

*・リスト、イテレーター処理系*

all(), any(), enumerate(), len(), range(), zip()

*・文字列系*

format(), ascii()

## インスタンス変数

reshape ,shape, dtype, column, index, mean_, var_

## 【問題3】標準化クラスをスクラッチで作成


In [6]:
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """

    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            学習データ
        """
        self.X = X
        self.mean_ = X.mean(axis = 0)
        self.var_ = X.var(axis = 0)

        pass

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X - self.mean_) / np.sqrt(self.var_) #sqrt　：　平方根の取得
        
        pass
        return X_scaled

In [7]:
import numpy as np
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


In [8]:
def __init__(self, copy=True, with_mean=True, with_std=True):
    self.with_mean = with_mean
    self.with_std = with_std
    self.copy = copy

In [30]:
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2

example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8


## 【問題4】 四則演算を行うクラスの作成


In [1]:
class ExampleClass():
    
    def __init__(self , value):
        assert type(value) != [int, float], "only int or float"
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    
    def add(self , value2):
        #self.value2 = value2
        self.value += value2
    
    def sub(self , value2):
        self.value -= value2
    
    def mul(self , value2):
        self.value *= value2
    
    def div(self , value2):
        self.value /= value2
        
        
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(5)
print("value : {}".format(example.value))
example.sub(5)
print("value : {}".format(example.value))
example.mul(5)
print("value : {}".format(example.value))
example.div(5)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 10
value : 5
value : 25
value : 5.0


In [3]:
example=ExampleClass(10)
example.sub(3)

初期値10が設定されました


In [40]:
#strの出力
example = ExampleClass(1)
print("value : {}".format(example.value))

初期値1が設定されました
value : 1


In [41]:
#floatの出力
example = ExampleClass(1.0)
print("value : {}".format(example.value))

初期値1.0が設定されました
value : 1.0


In [42]:
#エラーの出力
example = ExampleClass("aaa")
print("value : {}".format(example.value))

AssertionError: only int or float